**<h2> Time Series Analysis and Forecasting</h2>**

**<h3>Advanced time series analysis</h3>**

**Advanced Time Series Analysis Techniques**

Advanced time series analysis involves sophisticated methods to model and forecast time series data. These techniques are crucial in fields like finance, economics, weather forecasting, and any domain where temporal patterns are significant. Below, we explore some of the most prominent advanced time series analysis techniques: ARIMA, SARIMA, and Prophet.

In this session we will look at;

1. Advanced time series analysis techniques, including ARIMA, SARIMA, and Prophet.
2. Forecasting methods for hierarchical time series and multivariate time series.
2. Anomaly detection and intervention analysis in time series data.


**ARIMA**

ARIMA stands for Autogressive Intergrated Moving Average Model. It is a class model that forecasts time series data based on the past records. It uses lags and lags forecast errors.

**What is ARIMA model?**

ARIMA(Auto Regressive Integrated Moving Average) is a combination of 2 models AR(Auto Regressive) & MA(Moving Average). It has 3 hyperparameters - P(auto regressive lags), d(order of differentiation) and Q(moving avg.) which respectively comes from the AR, I & MA components. The AR part is correlation between prev & current time periods. To smooth out the noise, the MA part is used. The I part binds together the AR & MA parts.

There are different types of ARIMA models such as

1. ARIMA : Non-seasonal Autoregressive Integrated Moving Averages

2. SARIMA : Seasonal ARIMA

3. SARIMAX : Seasonal ARIMA with exogenous variables

If a time series, has seasonal patterns, then we need to add seasonal terms and it becomes SARIMA, short for Seasonal ARIMA.

**ARIMA IN PYTHON**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

#from statsmodels.tsa.stattools import adfuller
#from statsmodels.tsa.seasonal import seasonal_decompose
#from statsmodels.tsa.stattools import acf, pacf

#from statsmodels.tsa.arima.model import ARIMA
#from statsmodels.graphics.tsaplots import plot_predict

**Steps in carrying out ARIMA**

1. Visualize the time series analysis
2. Testing for stationarity

**What is Stationarity?**

Before applying any statistical model on a Time Series, the series has to be stationary, which means that, over different time periods,

1. It should have constant mean.

2. It should have constant variance or standard deviation.

3. Auto-covariance should not depend on time.


**Why does Timeseries has to be Stationary?**

Stationary data means mean and standard deviation of data does not change WRT time. The mean across many time periods is only informative if the expected value is the same across those time periods. We make the data stationary in case of ARIMA because the arima model looks at the past data to predict the future values.

Tests to check if a series is stationary or not:

There are 2 ways to check for Stationarity of a Timeseries:

1. Rolling Statistics - Plot the moving avg(mean) or moving standard deviation to see if it varies with time. It is a visual technique.

2. ADCF Test - Augmented Dickey–Fuller test is used to give us various values that can help in identifying stationarity. The Null hypothesis says that a Timeseries is non-stationary. It comprises of a Test Statistics & some critical values for some confidence levels. If the Test statistics is less than the critical values, we can reject the null hypothesis & say that the series is stationary. THE ADCF test also gives us a p-value. Acc to the null hypothesis, lower values of p is better.

**What Is ADCF test?**

In statistics and econometrics, an augmented Dickey–Fuller test (ADF) tests the null hypothesis that a unit root is present in a time series sample. The alternative hypothesis is different depending on which version of the test is used, but is usually stationarity or trend-stationarity. It is an augmented version of the Dickey–Fuller test for a larger and more complicated set of time series models.

The augmented Dickey–Fuller (ADF) statistic, used in the test, is a negative number. The more negative it is, the stronger the rejection of the hypothesis that there is a unit root at some level of confidence.

p value(0<=p<=1) should be as low as possible. Critical values at different confidence intervals should be close to the Test statistics value.

In [2]:
#Reading the data

data=pd.read_csv("D:/Desktop/airline-passengers.csv")
data.head()

     Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121

In [3]:
#renaming the columns

data.rename(columns={'#Passengers':'Passengers'},inplace=True)

In [4]:
data.head()

     Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121

In [5]:
#Converting the column month to the datetime value

#from datetime import datetime
#data['Month']=pd.to_datetime(data['Month'],infer_datetime_format=True)

In [6]:
data.head()

     Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121

In [7]:
#Setting  month as index and assigning it ti a new data frame
#airpassind = data.set_index('Month',inplace=False)

In [8]:
#airpassind.head()

In [9]:
data.head()

     Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121

In [10]:
#plotting our data

#plt.xlabel('Date')
#plt.ylabel('Number Of Air Passengers')
#plt.plot(airpassind)

In [11]:
#Testing for stationarity using the ADF Test

#adf_test = adfuller(airpassind['Passengers'])
# Output the results
#print('ADF Statistic: %f' % adf_test[0])
#print('p-value: %f' % adf_test[1])

From the result of the ADF test, we can see that our data is not stationary. Inorder to deal with the fact that our data is not stationary, we can apply some techniques listed below

1. Differencing the Series (once or more)
2. Take the log of the series
3. Take the nth root of the series
4. Combination of the above

In [12]:
#airpass_log = np.log(airpassind)
#plt.xlabel('Date')
#plt.ylabel('Number Of Air Passengers (log)')
#plt.plot(airpass_log)

In [13]:
#Testing for stationarity using the ADF Test

#adf_test = adfuller(airpass_log['Passengers'])
# Output the results
#print('ADF Statistic: %f' % adf_test[0])
#print('p-value: %f' % adf_test[1])

From the result if the adf test, we can see we still have non stationary data. We can try to improve this by using differectiation using the rolling mean and standard deviation

In [14]:
#rollmean_log = airpass_log.rolling(window=12).mean()
#rollstd_log = airpass_log.rolling(window=12).std()
#Create a new data frame with the diffferenciated values
#airpass_new = airpass_log - rollmean_log

In [15]:
#airpass_new.head()

In [16]:
#We can drop the null values
#airpass_new.dropna(inplace=True)
#airpass_new.head()

In [17]:
#plt.plot(airpass_new)

Now that we have the data, we can go a head and check for stationarity

In [18]:
#Testing for stationarity using the ADF Test

#adf_test = adfuller(airpass_new['Passengers'])
# Output the results
#print('ADF Statistic: %f' % adf_test[0])
#print('p-value: %f' % adf_test[1])

We can see from the test we have the p-value of 0.0225 meaning we can reject the null hypothesis that says the data is not statinary and conculude that the data is now stationary

we can also try to do the time shift transformation to our data

In [19]:
#airpass_log_diff = airpass_log - airpass_log.shift()
#airpass_log_diff.dropna(inplace=True)
#plt.plot(airpass_log_diff)

In [20]:
#Testing for stationarity using the ADF Test

#adf_test = adfuller(airpass_log_diff['Passengers'])
# Output the results
#print('ADF Statistic: %f' % adf_test[0])
#print('p-value: %f' % adf_test[1])

**ARIMA is AR + I + MA.**

- Before, we see an ARIMA model, let us check the results of the individual AR & MA model. These models will give a value of RSS (Sum of Square Residials). The lower the RSS values the better model.

In [21]:
# Define and fit the ARIMA model
#model1 = ARIMA(airpass_log_diff, order=(2,1,0))
#results_AR = model1.fit()

In [22]:
#def getRss(fitted_values):
 # rss = sum((fitted_values - airpass_log_diff['Passengers']) ** 2)
 # return rss

In [23]:
#def add(num1,num2):
#    total=num1+num2
#    return total

In [24]:
#add(20,40)

In [25]:
# Plot the original time series and the fitted values
#plt.plot(airpass_log_diff)
#plt.plot(results_AR.fittedvalues, color='red')
#plt.title('RSS: %.4f' % getRss(results_AR.fittedvalues))
#plt.show()

In [26]:
#model2 = ARIMA(airpass_log_diff, order=(0,1,2))
#results_MA = model2.fit()

#plt.plot(airpass_log_diff)
#plt.plot(results_MA.fittedvalues, color='red')
#plt.title('RSS: %.4f'%getRss(results_MA.fittedvalues))
#print('Plotting MA model')

## AR+I+MA = ARIMA Model
Making order = (2,1,2)

In [27]:
#model = ARIMA(airpass_log_diff, order=(5,1,5))
#results_ARIMA = model.fit()

#plt.plot(airpass_log_diff)
#plt.plot(results_ARIMA.fittedvalues, color='red')
#plt.title('RSS: %.4f'%getRss(results_ARIMA.fittedvalues))
#print('Plotting ARIMA model')

- By combining AR & MA into ARIMA, we see that RSS value has decreased from either case to 1.0292, indicating ARIMA to be better than its individual component models.
- With the ARIMA model built, we will now generate predictions. But, before we do any plots for predictions ,we need to reconvert the predictions back to original form. This is because, our model was built on log transformed data.

In [28]:
#def reverseLogTransformedDf(fittedValues, originalDf):
#  predictions_ARIMA_diff = pd.Series(fittedValues, copy=True)
#  predictions_ARIMA_diff_cumsum = predictions_ARIMA_diff.cumsum()
#  predictions_ARIMA_log = pd.Series(originalDf['Passengers'].iloc[0], index=originalDf.index)
#  predictions_ARIMA_log = predictions_ARIMA_log.add(predictions_ARIMA_diff_cumsum, fill_value=0)
#  predictions_ARIMA = np.exp(predictions_ARIMA_log)
#  return predictions_ARIMA

In [29]:
#predictions_ARIMA = reverseLogTransformedDf(results_ARIMA.fittedvalues, airpass_log)
#predictions_ARIMA.head()

In [30]:
#plt.plot(airpassind)
#plt.plot(predictions_ARIMA)

- We have 144 (existing data of 12 yrs in months) data points.
Now, we want to forecast for additional 10 yrs (10x12 months=120 data points).

**144+120 = 264 records/data points**

In [31]:
#fig, ax = plt.subplots()
#ax = airpass_log_diff.loc['1950':].plot(ax=ax)
#plot_predict(results_ARIMA, '1961', '1970', ax=ax)
#plt.show()

**SARIMA**

SARIMA (Seasonal AutoRegressive Integrated Moving Average) is an extension of ARIMA that supports univariate time series data with a seasonal component. SARIMA models are defined by both non-seasonal (p, d, q) and seasonal (P, D, Q, s) components.

p: The number of lag observations in the model.

d: The number of times that the raw observations are differenced.

q: The size of the moving average window.

P: The number of seasonal autoregressive terms.

D: The number of seasonal differences.

Q: The number of seasonal moving average terms

In [32]:
#import pandas as pd
#import numpy as np
#import matplotlib.pyplot as plt
#from statsmodels.tsa.statespace.sarimax import SARIMAX
#from statsmodels.datasets import get_rdataset
#from statsmodels.tsa.stattools import adfuller
#from statsmodels.stats.diagnostic import acorr_ljungbox

In [33]:
#Loading and preparing the data

# Load the AirPassengers dataset
#data = get_rdataset('AirPassengers', 'datasets').data
#data['time'] = pd.date_range(start='1949-01', periods=len(data), freq='M')
#data.set_index('time', inplace=True)
#data = data['value']

# Plot the time series
#data.plot(title='Monthly Totals of International Airline Passengers (1949-1960)')
#plt.show()

In [34]:
#data.head()

In [35]:
#sarima_model = SARIMAX(data, order=(1, 1, 1), seasonal_order=(1, 1, 1, 12))
#sarima_fitted = sarima_model.fit()

# Print the model summary
#print(sarima_fitted.summary())

Make Predictions
Use the fitted model to forecast future values.

In [36]:
# Forecast future values
#forecast_steps = 24
#forecast = sarima_fitted.get_forecast(steps=forecast_steps)
#forecast_index = pd.date_range(start=data.index[-1] + pd.Timedelta(days=1), periods=forecast_steps, freq='M')
#forecast_series = pd.Series(forecast.predicted_mean, index=forecast_index)

# Plot the observed data and the forecast
#plt.figure(figsize=(10, 6))
#plt.plot(data, label='Observed')
#plt.plot(forecast_series, label='Forecast', color='red')
#plt.legend()
#plt.show()

**Model Diagnostics**

Checking the residuals of the model to ensure no patterns are left.

In [37]:
# Plot residuals
#residuals = sarima_fitted.resid
#fig, ax = plt.subplots(1, 2, figsize=(12, 6))
#residuals.plot(ax=ax[0], title='Residuals')
#residuals.plot(kind='kde', ax=ax[1], title='Density')
#plt.show()

# Perform a Ljung-Box test
#ljung_box_test = acorr_ljungbox(residuals, lags=[10], return_df=True)
#print(ljung_box_test)

**Types of anomoly detection**

1. Point wise analmoly detection
2. Pattern wise anomally detection

Dataset: CPU utilization

Methods 
mean absolute deviation
Isolation forest
Local outlier factor